### ISSUE TITLE
can't use the package

### ISSUE THREAD

**Issue by djinnto** [MikaAK/angular-phoenix#4]
Hi,

I'm currently working on an angular app. I'm a front end developer, not yet completely fullstack competent...
I'm trying to use angular-phoenix but I can't seem to include the package correctly.

Here's what I've tried so far, with the results:

I've installed angular-phoenix with npm

1- using the linked js file directly:
in my index.html file:

```
<script type="text/javascript" src="https://raw.githubusercontent.com/phoenixframework/phoenix/847754db6b6b378ef4eaa5dfa7a8106e74db6a25/priv/static/phoenix.js"></script>
<script src="node_modules/angular-phoenix/src/angular-phoenix.js"></script>
```

Results in console:

> :8084/#/metrics:1 Refused to execute script from 'https://raw.githubusercontent.com/phoenixframework/phoenix/847754db6b6b378ef4eaa5dfa7a8106e74db6a25/priv/static/phoenix.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
> angular-phoenix.js:4 Uncaught ReferenceError: Phoenix is not defined

2- using the phoenix-js package:
2-1 calling the /lib/phoenix.js file
in my index.html file:

```
<script src="node_modules/phoenix-js/lib/phoenix.js" ></script>
<script src="node_modules/angular-phoenix/src/angular-phoenix.js"></script>
```

Results in console:

> phoenix.js:192 Uncaught SyntaxError: Unexpected token export
> angular-phoenix.js:4 Uncaught ReferenceError: Phoenix is not defined

2-2 calling the /dist/amd/main.js file
Results in console:

> main.js:1 Uncaught ReferenceError: define is not defined(anonymous function) @ main.js:1
> angular-phoenix.js:4 Uncaught ReferenceError: Phoenix is not defined

2-3 calling the /dist/cjs/main.js file
Results in console:

> main.js:90 Uncaught ReferenceError: exports is not defined(anonymous function) @ main.js:90
> angular-phoenix.js:4 Uncaught ReferenceError: Phoenix is not defined

2-4 calling the /dist/glob/main.js file
Results in console:

> angular-phoenix.js:4 Uncaught ReferenceError: Phoenix is not defined

Can anyone help me find out what I'm doing wrong please? I've been looking for a solution for hours... :,(

**Comment by MikaAK** [comment]
Read your own error you can't use github links like that.... 

```
:8084/#/metrics:1 Refused to execute script from 'https://raw.githubusercontent.com/phoenixframework/phoenix/847754db6b6b378ef4eaa5dfa7a8106e74db6a25/priv/static/phoenix.js' 
because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

**Comment by djinnto** [comment]
Thank you for your reply.
I'd read the error, all day actually. And the others too. But you seem to have erased the useful part of your reply, about Phoenix not being compiled. I still don't understand what I'm supposed to do to compile it or to get a compiled version, though. If you want to help.
Thank you.

**Comment by MikaAK** [comment]
@djinnto  [first link](http://bfy.tw/55nB), sorry if I'm a bit edgy this is really some basic things about github that a simple google search would have resolved. I erased my early comment because I misunderstood at a glance what was happening.

**Comment by djinnto** [comment]
No it's not, and no you didn't. I tried the raw github stuff last. My problem seems to be understanding how to compile Phoenix. So your edginess is just impatience and prejudice. 
I'm front end and I'm trying to go full stack and your being rude.
Thank you for your erased answer, it actually helped, luckily I got it in the email. It's not easy learning on your own while unemployed. At least I'm trying, and I spent several hours trying to understand (and using Google repeatedly to do so) before bothering you with my question.

**Comment by MikaAK** [comment]
The link you have given in the first post is the compiled version and should work in the browser. The error you have given me clearly states `because its MIME type ('text/plain') is not executable` the search from the [first link](http://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github) shows why MIME type of `text/plain` is happening and how to fix this. If you file is not loading, of course my package isn't going to work as you have gotten in your errors **Phoenix is not defined**

I'm sorry I cannot help you more with the information you have given me. I hope you fixed it :smile:

**Comment by djinnto** [comment]
Yes, I ended up using the raw github file (properly) and got the package working.
Thank you for replying again.
I'm having trouble adding params to the ws connection (outside of the config because using rootScope) so if the question isn't too dumb for you, your help would be most welcome! :)
